# Generated by Django 5.0.3 on 2024-03-27 22:06

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=64)),
                ('story_category', models.CharField(choices=[('pol', 'Politics'), ('art', 'Art'), ('tech', 'Technology New'), ('trivia', 'Trivial News')], max_length=64)),
                ('story_region', models.CharField(choices=[('uk', 'UK'), ('eu', 'EU'), ('w', 'World News')], max_length=64)),
                ('story_details', models.CharField(max_length=128)),
                ('author', models.CharField(default='', max_length=64)),
                ('story_date', models.CharField(default=datetime.date(2024, 3, 27), max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=64)),
                ('password', models.CharField(default='', max_length=64)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=64)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
